[tool.black]
line-length = 88
target-version = ['py37']
include = '\.pyi?$'

[tool.flake8]
max-line-length = 88
extend-ignore = "E203"  # Ignore whitespace before ':' (conflicts with Black)
per-file-ignores = []
exclude = [
    ".git",
    "__pycache__",
    "build",
    "dist",
]