# This file contains text cleaning functionality for processing PDF-to-text conversions.
# It handles chunking text into segments and using Gemini to clean up formatting issues
# like spurious line breaks, page headers, page numbers, etc.
#
# Key functions:
# - chunk_text: Splits text into ~5k word chunks for processing
# - clean_text_chunk: Uses Gemini to clean a single text chunk
# - clean_full_text: Orchestrates the cleaning of an entire document

import re
from typing import List
from src.utils.litellm_logger import litellm_completion


def chunk_text(text: str, target_words: int = 5000) -> List[str]:
    """
    Splits text into chunks of approximately target_words words.

    Args:
        text: The input text to chunk
        target_words: Target number of words per chunk (default 5000)

    Returns:
        List of text chunks
    """
    if not text.strip():
        return []

    words = text.split()
    if len(words) <= target_words:
        return [text]

    chunks = []
    current_chunk_words = []

    for word in words:
        current_chunk_words.append(word)

        # If we've reached the target size, look for a good break point
        if len(current_chunk_words) >= target_words:
            # Try to break at a paragraph boundary (double newline)
            chunk_text = " ".join(current_chunk_words)

            # Look for paragraph breaks in the last portion of the chunk
            last_500_chars = chunk_text[-500:] if len(chunk_text) > 500 else chunk_text
            paragraph_breaks = [
                m.start() for m in re.finditer(r"\n\s*\n", last_500_chars)
            ]

            if paragraph_breaks:
                # Use the last paragraph break as our split point
                break_point = len(chunk_text) - 500 + paragraph_breaks[-1] + 2
                chunks.append(chunk_text[:break_point].strip())

                # Start next chunk with remaining text
                remaining_text = chunk_text[break_point:].strip()
                current_chunk_words = remaining_text.split() if remaining_text else []
            else:
                # No good break point found, just split at target size
                chunks.append(chunk_text)
                current_chunk_words = []

    # Add any remaining words as the final chunk
    if current_chunk_words:
        chunks.append(" ".join(current_chunk_words))

    return chunks


def clean_text_chunk(text_chunk: str) -> str:
    """
    Uses Gemini to clean up a single text chunk.

    Args:
        text_chunk: The text chunk to clean

    Returns:
        The cleaned text, or original text if cleaning fails
    """
    if not text_chunk.strip():
        return text_chunk

    prompt = f"""Your job is to clean up the following text, which was generated by a PDF to text conversion process that did not handle line breaks, page headers, page numbers, and so on.

You should keep the first chapter heading of each chapter, but not chapter headings that are only there because there was a page break. Delete all other spurious lines as well, returning well-formatted text, verbatim from the source. You should have two linebreaks (i.e. one entire empty line) between each paragraph. However, do not modify the words of the text at all.

<TEXT BEGINS>
{text_chunk}
<TEXT ENDS>

Please respond immediately with the cleaned-up text:"""

    try:
        response = litellm_completion(
            model="gemini/gemini-2.5-flash-preview-05-20",
            messages=[{"role": "user", "content": prompt}],
            temperature=0,
        )

        if hasattr(response, "choices") and response.choices:
            cleaned_text = response.choices[0].message.content.strip()
            return cleaned_text if cleaned_text else text_chunk
        else:
            return text_chunk

    except Exception as e:
        print(f"Error cleaning text chunk: {e}")
        return text_chunk


def clean_full_text(text: str, target_chunk_size: int = 5000) -> str:
    """
    Cleans an entire text document by chunking it and cleaning each chunk.

    Args:
        text: The full text to clean
        target_chunk_size: Target words per chunk (default 5000)

    Returns:
        The fully cleaned text
    """
    if not text.strip():
        return text

    # Split into chunks
    chunks = chunk_text(text, target_chunk_size)

    # Clean each chunk
    cleaned_chunks = []
    for i, chunk in enumerate(chunks):
        print(f"Cleaning chunk {i+1}/{len(chunks)}...")
        cleaned_chunk = clean_text_chunk(chunk)
        cleaned_chunks.append(cleaned_chunk)

    # Join chunks back together with proper spacing
    return "\n\n".join(cleaned_chunks)
